# Generated by Django 4.1.2 on 2022-10-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlerating',
            unique_together=set(),
        ),
    ]
