# Generated by Django 4.1.2 on 2022-10-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_articlerating_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerating',
            name='rate',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
    ]
